### ISSUE TITLE
classify model files

### ISSUE THREAD

**Issue by Kevin-Zh-CS** [2021-ZJU-Software-engineering/software-engineering-backend#13]
After reading some Go projects, it seems appropriate to classify model files. Our group has filled in the attributes related to our group's functions, and other groups will continue to fill in according to their needs. Is this reasonable?

**Comment by AsterNighT** [comment]
Surely it is, and I believe there needs to be plenty discussions on that. Pls directly comment on the prs if you have got any suggestions or requirements in the part.
