### ISSUE TITLE
function `getAccountID()` is not exported

### ISSUE THREAD

**Issue by ziyue-pan** [2021-ZJU-Software-engineering/software-engineering-backend#35]
# Reproduce

![image](https://user-images.githubusercontent.com/50222787/121218878-bcf8f480-c8b5-11eb-837b-2a8baf7806e1.png)

# Possible Solution:

`getAccountID()`  →  `GetAccountID()`

**Comment by AsterNighT** [comment]
Use the middleware provided `c.Get("id")` instead.
