### ISSUE TITLE
`getAccountID()` does not return error on unauthorized request

### ISSUE THREAD

**Issue by ziyue-pan** [2021-ZJU-Software-engineering/software-engineering-backend#36]
# Reproduce

I gave **NO** payload.

![image](https://user-images.githubusercontent.com/50222787/121221012-ba979a00-c8b7-11eb-8f8f-2d9500518b01.png)

And it should have returned some error. But my trace shows that your `getAccountID()` returns nil ....

![image](https://user-images.githubusercontent.com/50222787/121220949-ac497e00-c8b7-11eb-8ca7-b6a50911c04a.png)

Is there some misunderstanding on `c.JSON` ?

![image](https://user-images.githubusercontent.com/50222787/121221348-0ea27e80-c8b8-11eb-9d3e-ecfc60a531df.png)

**Comment by AsterNighT** [comment]
Indeed

**Comment by AsterNighT** [comment]
I‘ll fix it
