### ISSUE TITLE
Design your database implementation detail and http API

### ISSUE THREAD

**Issue by AsterNighT** [2021-ZJU-Software-engineering/software-engineering-backend#8]
This will be a draft, you can edit this later, but it should not be too far from the final result.

Submit the database specification in a go file within `pkg/<a-short-name-for-your-group>/model.go`(like `pkg/cases/model.go`). 

And your api in `pkg/<a-short-name-for-your-group>/handler.go`(like `pkg/cases/handler.go`). 

Examples will be given by me later.

Pls surely let me know if you have any problem on how to do it.

The database due is 4.3. And the API being 4.10. We'll need a review on both on these, so you have to submit them about two days ahead. That is to say, 4.1 for the database and 4.8 for the API. 

Notice that you may have uncertainty when designing your database model for duplication with other groups. Be sure to have a mind on that and raise your questions in your first submit (before 4.1)

**Comment by AsterNighT** [comment]
The content is updated, PTAL. @FUTURETECH6 @Frank-Skywalker @PAN-Ziyue @RupertPaoZ @Estrella142857

**Comment by AsterNighT** [comment]
Any questions or doubts could be put forward now. If nobody has an objection the timeline will be set. And pls don't leave everything to ddl. Because your design may be rejected by me for several times before it passes.

**Comment by AsterNighT** [comment]
The examples are available now, PTAL

**Comment by AsterNighT** [comment]
I see some of you are having trouble getting started or in doubt about whether this should be placed in other groups' db model. That's ok. You can start by mapping your requirement to a struct, and filling everything you need (you can just ignore whether it will cause duplication or not if you are not sure, we can discuss this later).

**Comment by AsterNighT** [comment]
And for grammars, refer to [gorm](https://gorm.io) for specifications. You need not care about any database best practices for now. Just filling your blanks and make sure they are properly named (UpperCamelCase).

**Comment by futuretech6** [comment]
As for some wheels (parsing of HTTP req, parsing of URL, etc.), is there any rule for this? Need confirmation now? Or I should leave room for future modification?

**Comment by AsterNighT** [comment]
> As for some wheels (parsing of HTTP req, parsing of URL, etc.), is there any rule for this? Need confirmation now? Or I should leave room for future modification?

So Echo itself does not meet your demand? Could you brief your demand a bit because I don't quite come up with a scene?

**Comment by futuretech6** [comment]
> > As for some wheels (parsing of HTTP req, parsing of URL, etc.), is there any rule for this? Need confirmation now? Or I should leave room for future modification?
> 
> So Echo itself does not meet your demand? Could you brief your demand a bit because I don't quite come up with a scene?

Sry I negelet the tech stack part in README file, that's exactly what i want to know.

**Comment by AsterNighT** [comment]
Echo provide such functions like parsing http request to get params, queries, headers and body, as well as routing and logging, FYI.

**Comment by AsterNighT** [comment]
Take a look at #9 and the discussion for a good example.

**Comment by AsterNighT** [comment]
I see some of you are already working on the API specification, that's good. I will give a little guiding line here(and work as restrictions as well).
1. Use json for both end(you will receive and send only json in http body)
2. Stick to REST API (https://restfulapi.net/)
3. Fill up your swaggo comments first. Don't mind the implementation now.

**Comment by AsterNighT** [comment]
You may see that you get a red cross like ![image](https://user-images.githubusercontent.com/22937027/113015771-7352a600-91b0-11eb-8659-3121fb4b7d7a.png) in your pr. Pls check what is wrong by clicking it and make sure everything is green.

**Comment by AsterNighT** [comment]
This week we will settle down the API and submit them to the frontend. Pls be sure you catch on that.
